version: 2
jobs:
  build:
    context: vuong-io
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/vuong-io
    environment:
      HUGO_BUILD_DIR: public/
    steps:

      # install git
      - run: apt-get install git

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            apt-get install -y  python-pip python-dev build-essential 
            pip install awscli

      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              hugo deploy
            else
              echo "Not master branch, dry run only"
            fi 
